/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnamnesisAnalysisRouteImport } from './routes/api/anamnesis-analysis'
import { Route as ApiProtocolSuggestionRouteImport } from './routes/api/protocol-suggestion'
import { Route as ApiSessionSummaryRouteImport } from './routes/api/session-summary'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppProtocolosIndexRouteImport } from './routes/_authenticated/app/protocolos/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppProdutosIndexRouteImport } from './routes/_authenticated/app/produtos/index'
import { Route as AuthenticatedAppProcedimentosIndexRouteImport } from './routes/_authenticated/app/procedimentos/index'
import { Route as AuthenticatedAppClinicaIndexRouteImport } from './routes/_authenticated/app/clinica/index'
import { Route as AuthenticatedAppClientesIndexRouteImport } from './routes/_authenticated/app/clientes/index'
import { Route as AuthenticatedAppAnamnesesIndexRouteImport } from './routes/_authenticated/app/anamneses/index'
import { Route as AuthenticatedAppClientesIdRouteImport } from './routes/_authenticated/app/clientes/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnamnesisAnalysisRoute = ApiAnamnesisAnalysisRouteImport.update({
  id: '/api/anamnesis-analysis',
  path: '/api/anamnesis-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtocolSuggestionRoute = ApiProtocolSuggestionRouteImport.update({
  id: '/api/protocol-suggestion',
  path: '/api/protocol-suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionSummaryRoute = ApiSessionSummaryRouteImport.update({
  id: '/api/session-summary',
  path: '/api/session-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppProdutosIndexRoute =
  AuthenticatedAppProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProtocolosIndexRoute =
  AuthenticatedAppProtocolosIndexRouteImport.update({
    id: '/protocolos/',
    path: '/protocolos/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProcedimentosIndexRoute =
  AuthenticatedAppProcedimentosIndexRouteImport.update({
    id: '/procedimentos/',
    path: '/procedimentos/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppClinicaIndexRoute =
  AuthenticatedAppClinicaIndexRouteImport.update({
    id: '/clinica/',
    path: '/clinica/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppClientesIndexRoute =
  AuthenticatedAppClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAnamnesesIndexRoute =
  AuthenticatedAppAnamnesesIndexRouteImport.update({
    id: '/anamneses/',
    path: '/anamneses/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppClientesIdRoute =
  AuthenticatedAppClientesIdRouteImport.update({
    id: '/clientes/$id',
    path: '/clientes/$id',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/api/anamnesis-analysis': typeof ApiAnamnesisAnalysisRoute
  '/api/chat': typeof ApiChatRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/clientes/$id': typeof AuthenticatedAppClientesIdRoute
  '/app/anamneses/': typeof AuthenticatedAppAnamnesesIndexRoute
  '/app/clientes/': typeof AuthenticatedAppClientesIndexRoute
  '/app/clinica/': typeof AuthenticatedAppClinicaIndexRoute
  '/app/procedimentos/': typeof AuthenticatedAppProcedimentosIndexRoute
  '/app/produtos/': typeof AuthenticatedAppProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/anamnesis-analysis': typeof ApiAnamnesisAnalysisRoute
  '/api/chat': typeof ApiChatRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/clientes/$id': typeof AuthenticatedAppClientesIdRoute
  '/app/anamneses': typeof AuthenticatedAppAnamnesesIndexRoute
  '/app/clientes': typeof AuthenticatedAppClientesIndexRoute
  '/app/clinica': typeof AuthenticatedAppClinicaIndexRoute
  '/app/procedimentos': typeof AuthenticatedAppProcedimentosIndexRoute
  '/app/produtos': typeof AuthenticatedAppProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/api/anamnesis-analysis': typeof ApiAnamnesisAnalysisRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/clientes/$id': typeof AuthenticatedAppClientesIdRoute
  '/_authenticated/app/anamneses/': typeof AuthenticatedAppAnamnesesIndexRoute
  '/_authenticated/app/clientes/': typeof AuthenticatedAppClientesIndexRoute
  '/_authenticated/app/clinica/': typeof AuthenticatedAppClinicaIndexRoute
  '/_authenticated/app/procedimentos/': typeof AuthenticatedAppProcedimentosIndexRoute
  '/_authenticated/app/produtos/': typeof AuthenticatedAppProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/api/anamnesis-analysis'
    | '/api/chat'
    | '/app/'
    | '/app/clientes/$id'
    | '/app/anamneses/'
    | '/app/clientes/'
    | '/app/clinica/'
    | '/app/procedimentos/'
    | '/app/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/anamnesis-analysis'
    | '/api/chat'
    | '/app'
    | '/app/clientes/$id'
    | '/app/anamneses'
    | '/app/clientes'
    | '/app/clinica'
    | '/app/procedimentos'
    | '/app/produtos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/api/anamnesis-analysis'
    | '/api/chat'
    | '/_authenticated/app/'
    | '/_authenticated/app/clientes/$id'
    | '/_authenticated/app/anamneses/'
    | '/_authenticated/app/clientes/'
    | '/_authenticated/app/clinica/'
    | '/_authenticated/app/procedimentos/'
    | '/_authenticated/app/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAnamnesisAnalysisRoute: typeof ApiAnamnesisAnalysisRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiProtocolSuggestionRoute: typeof ApiProtocolSuggestionRoute
  ApiSessionSummaryRoute: typeof ApiSessionSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anamnesis-analysis': {
      id: '/api/anamnesis-analysis'
      path: '/api/anamnesis-analysis'
      fullPath: '/api/anamnesis-analysis'
      preLoaderRoute: typeof ApiAnamnesisAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/produtos/': {
      id: '/_authenticated/app/produtos/'
      path: '/produtos'
      fullPath: '/app/produtos/'
      preLoaderRoute: typeof AuthenticatedAppProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/procedimentos/': {
      id: '/_authenticated/app/procedimentos/'
      path: '/procedimentos'
      fullPath: '/app/procedimentos/'
      preLoaderRoute: typeof AuthenticatedAppProcedimentosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/clinica/': {
      id: '/_authenticated/app/clinica/'
      path: '/clinica'
      fullPath: '/app/clinica/'
      preLoaderRoute: typeof AuthenticatedAppClinicaIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/clientes/': {
      id: '/_authenticated/app/clientes/'
      path: '/clientes'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AuthenticatedAppClientesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/anamneses/': {
      id: '/_authenticated/app/anamneses/'
      path: '/anamneses'
      fullPath: '/app/anamneses/'
      preLoaderRoute: typeof AuthenticatedAppAnamnesesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/clientes/$id': {
      id: '/_authenticated/app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/app/clientes/$id'
      preLoaderRoute: typeof AuthenticatedAppClientesIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppClientesIdRoute: typeof AuthenticatedAppClientesIdRoute
  AuthenticatedAppAnamnesesIndexRoute: typeof AuthenticatedAppAnamnesesIndexRoute
  AuthenticatedAppClientesIndexRoute: typeof AuthenticatedAppClientesIndexRoute
  AuthenticatedAppClinicaIndexRoute: typeof AuthenticatedAppClinicaIndexRoute
  AuthenticatedAppProcedimentosIndexRoute: typeof AuthenticatedAppProcedimentosIndexRoute
  AuthenticatedAppProdutosIndexRoute: typeof AuthenticatedAppProdutosIndexRoute
  AuthenticatedAppProtocolosIndexRoute: typeof AuthenticatedAppProtocolosIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppClientesIdRoute: AuthenticatedAppClientesIdRoute,
  AuthenticatedAppAnamnesesIndexRoute: AuthenticatedAppAnamnesesIndexRoute,
  AuthenticatedAppClientesIndexRoute: AuthenticatedAppClientesIndexRoute,
  AuthenticatedAppClinicaIndexRoute: AuthenticatedAppClinicaIndexRoute,
  AuthenticatedAppProcedimentosIndexRoute:
    AuthenticatedAppProcedimentosIndexRoute,
  AuthenticatedAppProdutosIndexRoute: AuthenticatedAppProdutosIndexRoute,
  AuthenticatedAppProtocolosIndexRoute: AuthenticatedAppProtocolosIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAnamnesisAnalysisRoute: ApiAnamnesisAnalysisRoute,
  ApiChatRoute: ApiChatRoute,
  ApiProtocolSuggestionRoute: ApiProtocolSuggestionRoute,
  ApiSessionSummaryRoute: ApiSessionSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
